version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: prodpass
      POSTGRES_DB: weather_prod
    volumes:
      - pgdata_prod:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redisdata_prod:/data

volumes:
  pgdata_prod:
  redisdata_prod: